//
// Created by chaoqi on 2021/11/21.
//

#ifndef PRACTISE_CPLUSPLUS_NET_CELL_NET_UTILS_HPP
#define PRACTISE_CPLUSPLUS_NET_CELL_NET_UTILS_HPP

const uint32_t RECV_BUF_SIZE = 4096 * 20;


#endif //PRACTISE_CPLUSPLUS_NET_CELL_NET_UTILS_HPP
